### ISSUE TITLE
Unable to run HAAR-Cascade-Trainer-GUI on Ubuntu 20.04

### ISSUE THREAD

**Issue by ganezz** [amannirala13/HAAR-Cascade-Creator-OpenCV#8]
Hi Team,

I was trying to Run HAAR Cascade GUI Trainer 1.0  on my Ubuntu 20.04, 
I have followed the Requirement you mentioned.

When I was trying to run the app/main.py getting an error.

Starting...
git version 2.25.1
sh: 1: opencv_createsamples: not found
Environment ready!
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "main.py", line 187, in <module>
    main_window = tk.Tk()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0"

can you please help me, to run the Trainer application?.

**Comment by ImAli0** [comment]
I am having the same issue.
